### ISSUE TITLE
Use Environment?

### ISSUE THREAD

**Issue by cristeigabriela** [Akandesh/blazeddumper-cpp#1]
https://github.com/Akandesh/blazeddumper-cpp/blob/cdee945e5e75cef6308e0619a78d35aa468b8f5b/blazedumper/main.cpp#L45

This is unreliable for obvious reasons. An approach would be perhaps prompting the user to provide a folder which'd get set to local environment and perhaps stored for later usage?

Alternative, better way would be handling this in your current path by checking for the presence of a depot (you can leave some kind of mark which you'd check for to see if you have a prseent depot, and see if it's the latest), and use said depot for dumping. That is ideal for server usage.

**Comment by Akandesh** [comment]
Could also get steam path using the registry but this was never meant to be a dumper for the public, if people wants to use this then they simply have to change the path themselves etc.
